version: '3'
services:
  mysql:
    image: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: local-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      TZ: Asia/Jakarta
volumes:
  mysqldata:
    driver: local